-- Cups become a preference list stored on the Cocktail itself: comma-separated, best cup first, then fallbacks
-- (e.g. 'COUPE,MARTINI,WINE'). This replaces the Cup Sequence table, whose last cup was the serving glass,
-- so any existing rows are copied in reverse to put the serving glass first.
alter table cocktails add column cups varchar(200) not null default '';

update cocktails c
set cups = coalesce((select string_agg(cup, ',' order by position desc)
                     from cocktail_cups
                     where cocktail_id = c.id), '');

drop table cocktail_cups;

-- Seed migrations insert Cocktails with fixed ids, so recipes and their ingredients can refer to each other.
alter table cocktails alter column id set generated by default;
